### ISSUE TITLE
Incompatible library version for dlldiag?

### ISSUE THREAD

**Issue by FelipeDanfoss** [adamrehn/dll-diagnostics#3]
Hi, I'm running an exe with a specific environment variables and input arguments. I called the script like this: 
`python -m dlldiag graph <script_name_and_arguments>`

and got this:

```
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\lib\site-packages\dlldiag\__main__.py", line 9, in <module>
    main()
  File "C:\Python38\lib\site-packages\dlldiag\main.py", line 29, in main
    subcommands[subcommand]['function']()
  File "C:\Python38\lib\site-packages\dlldiag\subcommands\graph.py", line 333, in graph
    graph = GraphHelpers.constructGraph(logEntries)
  File "C:\Python38\lib\site-packages\dlldiag\subcommands\graph.py", line 91, in constructGraph
    graph = nx.OrderedMultiDiGraph()
AttributeError: module 'networkx' has no attribute 'OrderedMultiDiGraph'
```

I'm running this on Python 3.8.10

**Comment by FelipeDanfoss** [comment]
networkx version is simply >=2.5.1, I installed networkx 2.6.0 and the issue was fixed, the setup script could be updated.

P.S: This tool will save me so much time, thanks for your work!

Edit:
This was fixed at some point but the commit was not added to the latest release
